// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Project1 {
	
	
	public partial class Default {
		
		protected Project1.UserInfoBoxControl MyUserInfoBoxControl;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox text2;
		
		protected System.Web.UI.WebControls.DropDownList GreetList;
	}
}
